### ISSUE TITLE
Question on update

### ISSUE THREAD

**Issue by damiencarol** [PeterNotenboom/SwiftCodes#1]
How do you plan to manage updates ?

**Comment by PeterNotenboom** [comment]
Every week my scripts will crawl the site for any changes and updates the Json files.
If everything is the same, the Json is generated the same, so no changes can be pushed.

If anything in the Json changed, i get notified and can Push it to Github.
My "crawl-script" will be on here too, as soon as i make sense of the ugly code, then anyone can update as they want.
But there doesn't seem to be much changes going on in the SWIFT codes.

**Comment by PeterNotenboom** [comment]
A new year has started, so there's a lot of changes at this moment (Updating right now).

I also just added an Image to the README.
That image shows the timestamp when the Swift codes have been checked.

**Comment by damiencarol** [comment]
@PeterNotenboom ok, good.
