### ISSUE TITLE
Passive participants

### ISSUE THREAD

**Issue by catsAND** [PeterNotenboom/SwiftCodes#2]
Hello, thanks for list. Maybe better parse from https://www.swiftcodes.info/ ? Its identical site, but only with passive participants.

**Comment by PeterNotenboom** [comment]
Thanks for your suggestion!
I don't think it will be a problem to crawl that site. 
Perhaps i can combine or grab it as fallback. I'll make a comparison to see if there's any difference between the 2 sites on Swiftcodes. If not, I'll use it as fallback just in case.

**Comment by catsAND** [comment]
Hello. How progress?

**Comment by PeterNotenboom** [comment]
Today I looked into it and see that there's a larger database, so I'm switching to swiftcodes.info.
I will update the JSON files today :+1:
