### ISSUE TITLE
Composer.json

### ISSUE THREAD

**Issue by vercotux** [PeterNotenboom/SwiftCodes#4]
Would it be possible to add a composer.json file so that the project can be published on [Packagist](https://packagist.org/) and included by PHP developers as a composer dependency? It would be incredibly useful.

**Comment by PeterNotenboom** [comment]
You're right!

Magic is done:
https://packagist.org/packages/pn/swiftcodes

**Comment by vercotux** [comment]
Pure awesomeness!
