### ISSUE TITLE
Removal request of sensitive content related to Banco Safra/Safra Bank

### ISSUE THREAD

**Issue by legalaxur** [PeterNotenboom/SwiftCodes#5]
Dear Sir/Madam,

Our company, AXUR, represents Banco Safra in issues involving the violation of intellectual property and fraud on the Internet.

Banco Safra is the only company authorized to use the trademark SAFRA and owns or licenses numerous trademark registrations worldwide, including, but not limited to the following registration number INPI: 006033504, 810857448, 817834540, 818693363, 820513580, 818473266, 820695858, USPTO: 3150478, 1806382, OHIM: 006017669.

The trademarks, logos, words and phrases registered by Banco Safra shall be exclusively used by Banco Safra and any other use by a third party constitutes a trademark infringement.

It has come to our attention that the reported repository provides related content to the trademark SAFRA without having obtained prior written authorization from Banco Safra. More specifically, this content discloses SENSITIVE DATA from our client or its customer, creating a Likelihood of Confusion between the trademark SAFRA and the reported content.

Here follows the specific lines: 356, 357, 358, 359, 360, 363, 364, 365, 366, 367, 580, 581, 582, 583, 584.

Furthermore, by misusing the trademark SAFRA on your repository, you are also diluting its use, because it weakens the ability of brand identification as a single source of research and may lead consumers to believe that there is some association between Banco Safra and your repository.

Official Website: https://www.safra.com.br/

Considering the violation of intellectual property rights of Banco Safra on your website, we kindly request that you remove all content available on the attached URL(s) which use the abovementioned trademark without having obtained prior authorization.

In order to avoid a lawsuit from a federal court, please, send confirmation that this email was received along with your guarantee to comply with the requests reported above.

Under penalty of perjury, we affirm that AXUR is authorized to act on behalf of the Banco Safra and this notification is in accordance with International Regulations of Internet and Intellectual Property Offices.

Should you require further information or should you prefer to discuss this issue, please do not hesitate to contact us through the e-mail address listed on the signature of this message.

Sincerely,

AXUR
Legal Team
legal@axur.com

ATTACHMENT:
https://github.com/PeterNotenboom/SwiftCodes/blob/master/AllCountries/LU.json

**Comment by PeterNotenboom** [comment]
Hi AXUR Legal Team,

Thanks for contacting me.
The lines are removed from the repository/file. I complied with your request.

Note: those Swift codes are publicly available on around 123+ sites (Google search).
Thanks!
